## Conditional

In [2]:
import numpy as np

In [3]:
arr=np.array( [2,4,5,1,3,6,7,20])
print (arr>2)
b=arr[arr%2==0] 
print ( b , type(b))
#Check and creates a boolean list. Then prints all True

[False  True  True False  True  True  True  True]
[ 2  4  6 20] <class 'numpy.ndarray'>


In [12]:
a = np.arange(1,15)

In [13]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [14]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [16]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

#### Multiple Conditions

In [18]:
(a>4) & (a%2==0)

array([False, False, False, False, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [19]:
a[(a>4) & (a%2==0)]

array([ 6,  8, 10, 12, 14])

#### Concat
- Vertical Stacking  - Column number must be same
- Horizontal Stacking - Row number

In [4]:
a = np.array ( [ [1,2,3,4] , [6,7,0,1]])
b= np.array( [[1,3,5,7], [2,4,6,8],[9,8,7,6],[2,3,4,5]])
print (a , b, np.vstack((a,b)) , sep="\n")

[[1 2 3 4]
 [6 7 0 1]]
[[1 3 5 7]
 [2 4 6 8]
 [9 8 7 6]
 [2 3 4 5]]
[[1 2 3 4]
 [6 7 0 1]
 [1 3 5 7]
 [2 4 6 8]
 [9 8 7 6]
 [2 3 4 5]]


In [5]:
a = np.array ( [ [1,2,3,4] , [6,7,0,1]])
b= np.array( [[1,3,5,7,0], [2,4,6,8,9]])
c= np.hstack((a,b))
print (a , b, np.hstack((a,b)) , sep="\n")
c

[[1 2 3 4]
 [6 7 0 1]]
[[1 3 5 7 0]
 [2 4 6 8 9]]
[[1 2 3 4 1 3 5 7 0]
 [6 7 0 1 2 4 6 8 9]]


array([[1, 2, 3, 4, 1, 3, 5, 7, 0],
       [6, 7, 0, 1, 2, 4, 6, 8, 9]])

##### hsplit/vsplit

https://docs.scipy.org/doc/numpy/reference/generated/numpy.hsplit.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.vsplit.html

In [7]:
a = np.array([[1, 2, 3, 4, 1,a 3, 5, 7, 0],
       [6, 7, 0, 1, 2, 4, 6, 8, 9]])

SyntaxError: invalid syntax (<ipython-input-7-8070dbf60d68>, line 1)

##### Ravel/ Flatten
- To 1-D

In [20]:
a = np.array([[1, 2, 3, 4, 1,0], [6, 7, 0, 1,  8, 9] , [2, 4, 6, 8, 9,3 ]]) 
a

array([[1, 2, 3, 4, 1, 0],
       [6, 7, 0, 1, 8, 9],
       [2, 4, 6, 8, 9, 3]])

In [21]:
a.flatten()

array([1, 2, 3, 4, 1, 0, 6, 7, 0, 1, 8, 9, 2, 4, 6, 8, 9, 3])

In [22]:
a.ravel()

array([1, 2, 3, 4, 1, 0, 6, 7, 0, 1, 8, 9, 2, 4, 6, 8, 9, 3])