#### Linspace

np.linspace (start, end, no of elemrnts between two values )

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html

In [2]:
import numpy as np
np.linspace(1,2,6).reshape(2,3) 

array([[1. , 1.2, 1.4],
       [1.6, 1.8, 2. ]])

- when we simualte  a data, we use them
- Return type is an array

In [4]:
np.linspace(1,500,7)

array([  1.        ,  84.16666667, 167.33333333, 250.5       ,
       333.66666667, 416.83333333, 500.        ])

##### dtype : dtype, optional
The type of the output array. If dtype is not given, infer the data type from the other input arguments.

In [5]:
np.linspace(1,500,7, dtype=np.int)

array([  1,  84, 167, 250, 333, 416, 500])

##### endpoint : bool, optional
If True, stop is the last sample. Otherwise, it is not included. Default is True.

In [7]:
print (np.linspace(1,100,11,endpoint = False ))

[ 1. 10. 19. 28. 37. 46. 55. 64. 73. 82. 91.]


In [8]:
print (np.linspace(1,100,11 ))

[  1.   10.9  20.8  30.7  40.6  50.5  60.4  70.3  80.2  90.1 100. ]
