- 2D array
- List of List or using " ; "

In [2]:
import numpy as np
mat= np.matrix ( ' [64, 34 ; 25 ,89]')  # USing ";"
print (mat)

[[64 34]
 [25 89]]


In [4]:
mat = np.matrix ( [[64,34] , [25,89] ])  # List of List
print (mat)

[[64 34]
 [25 89]]


In [6]:
mat = np.matrix ( [[64,34] , ( 25,89 )])  # A list and tuple
print (mat)  

[[64 34]
 [25 89]]


In [8]:
mat = np.matrix ( [[64,34,0] , [25,89,45] , [3,76,49]]) # 3 x 3
print (mat)
print (type(mat))

[[64 34  0]
 [25 89 45]
 [ 3 76 49]]
<class 'numpy.matrix'>


#### resize

- Creates a dimension firt and then fils them with available elements

In [13]:
a = np.array( [1,2,3,4,5,6])
np. resize( a ,(4,5))

array([[1, 2, 3, 4, 5],
       [6, 1, 2, 3, 4],
       [5, 6, 1, 2, 3],
       [4, 5, 6, 1, 2]])

In [15]:
a= np.arange(1,11)
#5,5 6,4

print ( np.resize(a,(5,5)))
print ( np.resize(a,(6,4)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]
 [ 1  2  3  4]]


In [16]:
a= np.arange(1,11)
print ( sum(a) , a.sum ())

55

In [20]:
a= np.arange(1,11)
print ( max(a) , a.max(), min (a) , a.min() )

10 10 1 1


#### numpy.sum()

axis =1  : Row
axis = 0 : Column

https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html

In [31]:
import numpy as np

array1 = np.array(
    [[1, 2],
     [3, 4],
     [5, 6]])

col = np.sum(array1, axis=0)  # Default is "0", Column addition
print('Sum of elements at 0-axis i.e Columnwise is ',col)

row = np.sum(array1, axis=1)
print('Sum of elements at 1-axis i.e row-wise  is ', row )

col = array1.sum( axis=0)  # Default is "0", Column addition
print('Sum of elements at 0-axis i.e Columnwise is ',col)

row = array1.sum( axis=1)
print('Sum of elements at 1-axis i.e row-wise  is ', row )

print(array1.sum())

Sum of elements at 0-axis i.e Columnwise is  [ 9 12]
Sum of elements at 1-axis i.e row-wise  is  [ 3  7 11]
Sum of elements at 0-axis i.e Columnwise is  [ 9 12]
Sum of elements at 1-axis i.e row-wise  is  [ 3  7 11]
21


In [34]:
print(array1.sum()  , sum(array1) )   # sum(a )It will give Row  addition

21 [ 9 12]


##### np.sqrt()

In [35]:
arr = np.array(
    [[1, 2],
     [3, 4],
     [5, 6]])

np.sqrt(arr)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [38]:
np.sqrt([1,4,9])

array([1., 2., 3.])

In [40]:
np.sqrt([4, -1, -3+4J])  # Sqare roots of complex numbers

array([2.+0.j, 0.+1.j, 1.+2.j])

In [36]:
np.mean(arr)

3.5

##### np.square()

In [37]:
np.square(arr)

array([[ 1,  4],
       [ 9, 16],
       [25, 36]], dtype=int32)

In [47]:
np.square([-1j, 1])  #Complex numbers

array([-1.+0.j,  1.+0.j])

##### Arithmetic operations in arrays

In [45]:
a= np.arange(4).reshape(2,2)
b= np.arange(5,9).reshape(2,2)
c=a+b
print(a,b,c, sep="\n")

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]
[[ 5  7]
 [ 9 11]]


In [51]:
a= np.arange(4).reshape(2,2)
b= np.arange(5,12,2).reshape(2,2)
c=b-a
print(a,b,c, sep="\n")

[[0 1]
 [2 3]]
[[ 5  7]
 [ 9 11]]
[[5 6]
 [7 8]]


In [53]:
a= np.arange(4).reshape(2,2)
b= np.arange(5,12,2).reshape(2,2)
c=b/a
print(a,b,c, sep="\n")

[[0 1]
 [2 3]]
[[ 5  7]
 [ 9 11]]
[[       inf 7.        ]
 [4.5        3.66666667]]


C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


#### Multiplcation using dot product  - Matrix Multilication


In [21]:
    a= np.arange(6).reshape(2,3)
    b= np.arange(6).reshape(3,2)
    c= np.dot(a,b)
    d=a@b
    print(a,b,c, d,sep="\n")

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]]
[[10 13]
 [28 40]]


#### Broadcasting:
    n x m , i x j -->  either n==i or m==j  /n==i,m==j
    and atleat one's shape should be 1

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. 
Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.
Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations.
There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:



In [63]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
print(a*b)

[2. 4. 6.]


In [64]:
a = np.array([1.0, 2.0, 3.0])
b=9
a*b

array([ 9., 18., 27.])

https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

When rows are same, row multiplication

In [17]:
a = np.array ( [[1,2,3] , [4,5,6] ,[7,8,9]])
b = np.array ( [[10,20,30]])
c = a* b
print(a)
print(b)
print (a.shape,b.shape)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]]
(3, 3) (1, 3)
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [18]:
a = np.array ( [[1,2,3] , [4,5,6] ,[7,8,9]])  
b = np.array ( [[10,20,30]]) .reshape(3,1)
c = a*b
print(a)
print(b)
print (a.shape,b.shape)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10]
 [20]
 [30]]
(3, 3) (3, 1)
[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


In [22]:
#ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 
a = np.array ( [[1,2,3] , [4,5,6] ,[7,8,9]])
b = np.array ( [[10,20,30], [1,2,3]])
c = a* b
print(c)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

#### In matrix  a.*b is matrix multiplication

#### Transpose

In [76]:
a = np.transpose (np.array ( [[1,2,3] , [4,5,6] ,[7,8,9]]))
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Iteration



In [72]:
a = np.array ( [[1,2,3] , [4,5,6] ,[7,8,9]])

for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9


In [6]:
a=np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
a[2:,1:2]

array([[ 8],
       [11]])