1D- List
2D - List of List
3D - List of List of lists

#### 1- D

In [13]:
import numpy as np
a = np.array([1,7,4])
print(a)
print( "Shape :"  ,a.shape)
print( "Data Type :"  ,a.dtype) 
print("Dim : " , a.ndim)
print( "Size:" , a.size)
print( "Item Size:" , a.itemsize)

[1 7 4]
Shape : (3,)
Data Type : int32
Dim :  1
Size: 3
Item Size: 4


#### 2 - D

In [12]:
a = np.array ( [[ 1,2,3] , [6,7,8]])
print(a)
print( "Shape :"  ,a.shape)
print( "Data Type :"  ,a.dtype) 
print("Dim : " , a.ndim)
print( "Size:" , a.size)
print( "Item Size:" , a.itemsize)

[[1 2 3]
 [6 7 8]]
Shape : (2, 3)
Data Type : int32
Dim :  2
Size: 6
Item Size: 4


In [15]:
  #row 5 column 4
a = np.array ( [ [ 1,2,3,3] , [6,7,8,8] ,[4,6,7,8] , [3,7,0,4] , [4,5,8,2] ] )
print(a)
print( "Shape :"  ,a.shape)
print( "Data Type :"  ,a.dtype) 
print("Dim : " , a.ndim)
print( "Size:" , a.size)
print( "Item Size:" , a.itemsize)

[[1 2 3 3]
 [6 7 8 8]
 [4 6 7 8]
 [3 7 0 4]
 [4 5 8 2]]
Shape : (5, 4)
Data Type : int32
Dim :  2
Size: 20
Item Size: 4


In [17]:
  # 3 x 1
a = np.array ( [ [1],[5],[7] ] )
print(a)
print( "Shape :"  ,a.shape)
print( "Data Type :"  ,a.dtype) 
print("Dim : " , a.ndim)
print( "Size:" , a.size)
print( "Item Size:" , a.itemsize)

[[1]
 [5]
 [7]]
Shape : (3, 1)
Data Type : int32
Dim :  2
Size: 3
Item Size: 4


#### 3 - D

In [18]:
a= [[ [ 1,2,3,3] , [6,7,8,8] ,[4,6,7,8] , [3,7,0,4] , [4,5,8,2] ] , [ [ 1,2,3,3] , [6,7,8,8] ,[4,6,7,8] , [3,7,0,4] , [4,5,8,2] ]]
a = np.array ( a )
print(a)
print( "Shape :"  ,a.shape)
print( "Data Type :"  ,a.dtype) 
print("Dim : " , a.ndim)
print( "Size:" , a.size)
print( "Item Size:" , a.itemsize)

[[[1 2 3 3]
  [6 7 8 8]
  [4 6 7 8]
  [3 7 0 4]
  [4 5 8 2]]

 [[1 2 3 3]
  [6 7 8 8]
  [4 6 7 8]
  [3 7 0 4]
  [4 5 8 2]]]
Shape : (2, 5, 4)
Data Type : int32
Dim :  3
Size: 40
Item Size: 4


#### Reshape()

- Sum of elements should match the product of rows and columns

In [21]:
a = np.array([1,7,4,6])
print(a)
print( "Shape :"  ,a.shape)
print( "Data Type :"  ,a.dtype) 
print("Dim : " , a.ndim)
print( "Size:" , a.size)
print( "Item Size:" , a.itemsize)
print()
a = a.reshape(2,2)
print(a)
print( "Shape :"  ,a.shape)
print( "Data Type :"  ,a.dtype) 
print("Dim : " , a.ndim)
print( "Size:" , a.size)
print( "Item Size:" , a.itemsize)

[1 7 4 6]
Shape : (4,)
Data Type : int32
Dim :  1
Size: 4
Item Size: 4

[[1 7]
 [4 6]]
Shape : (2, 2)
Data Type : int32
Dim :  2
Size: 4
Item Size: 4


##### Convert a range of 27 to 3 D

In [27]:
a =np.arange(27)
a=a.reshape(3,3,3)
print(a)
print( "Shape :"  ,a.shape)
print( "Data Type :"  ,a.dtype) 
print("Dim : " , a.ndim)
print( "Size:" , a.size)
print( "Item Size:" , a.itemsize)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Shape : (3, 3, 3)
Data Type : int32
Dim :  3
Size: 27
Item Size: 4


In [34]:
a= np.arange(24)
print(a.reshape(2,3,4))
print("==================")
print(a.reshape(2,4,3))
print("==================")
print(a.reshape(3,2,4))
print("==================")
print(a.reshape(3,4,2))
print("==================")
print(a.reshape(4,3,2))
print("==================")
print(a.reshape(4,2,3))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


#### Data Slicing

In [61]:
a= np.arange(15).reshape(3,5)
print(a)
print()
print(a[0])
print(a[0,1])
print("First Column:")
print(a[:,0])
print("First two Rows: ")
print(a[0:2:1])
print("First two Rows: ")
print(a[:2])
print("First two Rows and two columns: ")
print(a[0:2:1,0:2:1])
print("First two Rows and two columns: ")
print(a[:2,:2])
print("4th columns: ")
print(a[:,3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[0 1 2 3 4]
1
First Column:
[ 0  5 10]
First two Rows: 
[[0 1 2 3 4]
 [5 6 7 8 9]]
First two Rows: 
[[0 1 2 3 4]
 [5 6 7 8 9]]
First two Rows and two columns: 
[[0 1]
 [5 6]]
First two Rows and two columns: 
[[0 1]
 [5 6]]
4th columns: 
[ 3  8 13]


In [74]:
a=np.arange(1,10).reshape(3,3)
print(a)
print( a[ 1:3 ,0:2])
print ( a [ 1:3 , 1:3])
print( a [ : , 1:2])
print(a[1:3,0:1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]
[[5 6]
 [8 9]]
[[2]
 [5]
 [8]]
[[4]
 [7]]


In [77]:
print( a [0:3 , 0:3:2])

print( a [: ,::2] )

print (a[::2 ])

[[1 3]
 [4 6]
 [7 9]]
[[1 3]
 [4 6]
 [7 9]]
[[1 2 3]
 [7 8 9]]
