In [1]:
import numpy as np
a = np.array([[1, 2, 3, 4, 1,0], [6, 7, 0, 1,  8, 9] , [2, 4, 6, 8, 9,3 ]]) 

In [2]:
a

array([[1, 2, 3, 4, 1, 0],
       [6, 7, 0, 1, 8, 9],
       [2, 4, 6, 8, 9, 3]])

In [3]:
for i in np.nditer(a):
    print(i)

1
2
3
4
1
0
6
7
0
1
8
9
2
4
6
8
9
3


In [5]:
for i in a:
    print( i)

[1 2 3 4 1 0]
[6 7 0 1 8 9]
[2 4 6 8 9 3]
