# IN CLASS LAB EXERCISES - 01

#### Import NumPy package as np

In [2]:
import numpy as np

####  01.  Create an empty array of 20 0's and replace the 4th object with the number 5

In [3]:
a = np.zeros(20)
a[3]=5
a

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

--------

#### 02. Create an array of 20 1's and store it as a variable named array_master. Copy the same array into another variable named array_copy

In [5]:
array_master = np.ones(20)
array_copy = np.copy(array_master)
print(array_master , array_copy ,sep = "\n")

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


--------

#### 03.Create an array containing 30 1's and broadcast all the one's to the value 100

In [6]:
a= np.ones(30,dtype = np.int) *100
a

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

----------------------------------------------------

#### 04. Create an array of integers starting from 21 until 31 and name it as array1

####  ---     Create an array of integers starting from 11 until 21 and name it array2

####  ---    Calculate the difference between array1 and array2

In [7]:
a= np.arange(21,32)
b= np.arange(11,22)
print(a-b)

[10 10 10 10 10 10 10 10 10 10 10]


---------------------------------------------

#### 05. Create an array of all even integers from 2 to 10 and name it a1

#### --   Create an array of all even integers from 22 to 30 and name it a2

####    a) Use the 2 arrays as rows and create a matrix [ Hint - Use stack function from numpy ]

In [39]:
a1 = np.arange(2,11,2)
a2 = np.arange(22,31,2)
print(np.vstack((a1,a2)))
np.vstack((a1,a2))

[[ 2  4  6  8 10]
 [22 24 26 28 30]]


array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

-----------------------

####  b) Use the 2 arrays as columns and create a matrix [ Hint - Use column_stack function from numpy ]

In [13]:
a1 = np.arange(2,11,2)
a2 = np.arange(22,31,2)
print( np.hstack ((a1,a2)))

[ 2  4  6  8 10 22 24 26 28 30]


--------------

#### 06. Create a 5x6 matrix with values ranging from 0 to 29 and retrieve the value intersecting at 2nd row and 3rd column

In [47]:
a = np.arange(30).reshape(5,6)
print(a)
print( a [1,2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
8


--------------------

#### 07. Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [55]:
#Method 1
a = np.identity(10, dtype = np.int)
a [a ==0] =21
print(a)

[[ 1 21 21 21 21 21 21 21 21 21]
 [21  1 21 21 21 21 21 21 21 21]
 [21 21  1 21 21 21 21 21 21 21]
 [21 21 21  1 21 21 21 21 21 21]
 [21 21 21 21  1 21 21 21 21 21]
 [21 21 21 21 21  1 21 21 21 21]
 [21 21 21 21 21 21  1 21 21 21]
 [21 21 21 21 21 21 21  1 21 21]
 [21 21 21 21 21 21 21 21  1 21]
 [21 21 21 21 21 21 21 21 21  1]]


In [3]:
#Method2
a = np.identity(10, dtype = np.int)
print(a)
print(np.where ( a==0 , 21, a))

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
[[ 1 21 21 21 21 21 21 21 21 21]
 [21  1 21 21 21 21 21 21 21 21]
 [21 21  1 21 21 21 21 21 21 21]
 [21 21 21  1 21 21 21 21 21 21]
 [21 21 21 21  1 21 21 21 21 21]
 [21 21 21 21 21  1 21 21 21 21]
 [21 21 21 21 21 21  1 21 21 21]
 [21 21 21 21 21 21 21  1 21 21]
 [21 21 21 21 21 21 21 21  1 21]
 [21 21 21 21 21 21 21 21 21  1]]


--------------------

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

#### 08. Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [81]:
a=np.random.rand(10)
a>0.2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

-------------------

#### 09. Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

In [63]:
a = np.random.standard_normal(size = (5,2) )
a

array([[-0.20333556, -0.88625832],
       [ 0.28801215,  1.20478268],
       [-0.50475336,  0.5952841 ],
       [-0.65974815, -0.54065954],
       [-0.39073266, -1.33004321]])

-----------------------------

#### 10. Create an array of 30 linearly spaced points between 0 and 100:

In [37]:
a = np.linspace(0,100,30)
a

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

---------------------------

## Numpy Indexing and Selections

#### 11. Using the below given Matrix, generate the output for the below questions.

[11,17,27,9,64] ,[7,13,2,14,55] , [1,16,12,0,5] ,[1,2,11,22,5], [67,73,21,67,78]

In [86]:
a=np. array([[11,17,27,9,64] ,[7,13,2,14,55] , [1,16,12,0,5] ,[1,2,11,22,5], [67,73,21,67,78]])
print(a)

[[11 17 27  9 64]
 [ 7 13  2 14 55]
 [ 1 16 12  0  5]
 [ 1  2 11 22  5]
 [67 73 21 67 78]]


----------------

#### a) Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [76]:
a [3:5 , :3]

array([[ 1,  2, 11],
       [67, 73, 21]])

------

#### b) Retrieve the value 55 from the above matrix using index & selection technique

In [77]:
a[1,4]

55

--------------

#### c) Retrieve the values from the 3rd column in the above matrix

In [88]:
a[:,2]

array([27,  2, 12, 11, 21])

---------------

#### d) Retrieve the values from the 4th row in the above matrix

In [79]:
a[3]

array([ 1,  2, 11, 22,  5])

-----------------

#### e) Retrieve values from the 2nd & 4th rows in the above matrix

In [89]:
a[1:5:2]

array([[ 7, 13,  2, 14, 55],
       [ 1,  2, 11, 22,  5]])

--------------

### Calculate the following values for the given matrix

In [90]:
a=np. array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30] , [1,2,3,4,5]])
a

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30],
       [ 1,  2,  3,  4,  5]])

#### a) Calculate sum of all the values in the matrix

In [91]:
np.sum(a)

175

--------------

#### b) Calculate standard deviation of all the values in the matrix

In [92]:
np.std(a)

10.498677165349081

------

#### c) Calculate the variance of all values in the matrix

In [93]:
np.var(a)

110.22222222222221

-----------

#### d) Calculate the mean of all values in the matrix

In [94]:
np.mean(a)

11.666666666666666

-------------

#### e) Retrieve the largest number from the matrix

In [95]:
np.max(a)

30

--------------

#### f) Retrieve the smallest number from the matrix

In [96]:
np.min(a)

1

-------

# -------------------------------- HAPPY LEARNING -------------------------------

--------------------------------