#### ndarray.shape
This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [18]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)
print (a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [10]:
a2 = np.array  ([[1,2,3] , [4,6] ])
print(a2)

[list([1, 2, 3]) list([4, 6])]


In [14]:
a2 = np.array  ([[1,2,3] , [4,6, 5] ])
print(a2)
print( a2.shape)
a2 =a2. reshape (3,2)
print(a2)
print( a2.shape)

[[1 2 3]
 [4 6 5]]
(2, 3)
[[1 2]
 [3 4]
 [6 5]]
(3, 2)


In [3]:
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print( a )

[[1 2]
 [3 4]
 [5 6]]


##### NumPy also provides a reshape function to resize an array.

In [15]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print( b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print( b)

##### Zeros

https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html

In [25]:
a= np.zeros(8)
a

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
a = np.zeros((5,4) )
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [48]:
a = np.zeros((5,4) , dtype = np.int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [53]:
a[2,2:3] =5
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 5 0]
 [0 0 0 0]
 [0 0 0 0]]


##### Ones()

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html

In [27]:
a = np.ones(3)
a

array([1., 1., 1.])

In [28]:
a = np.ones((5,4) , dtype = np.int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [33]:
s = (2,2)
a= np.ones(s)  # Takes a tuple/list - shape as argument
a

array([[1., 1.],
       [1., 1.]])

In [31]:
s = [2,3,4]
a= np.ones(s)  # Takes a tuple as argument
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

##### Special functions

In [39]:
a= np.arange(2,8)
np.log(a)  #Log base e

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015])

In [40]:
np.log10(a)

array([0.30103   , 0.47712125, 0.60205999, 0.69897   , 0.77815125,
       0.84509804])

In [41]:
np.log2(a)

array([1.        , 1.5849625 , 2.        , 2.32192809, 2.5849625 ,
       2.80735492])

In [42]:
np.exp(a) 

array([   7.3890561 ,   20.08553692,   54.59815003,  148.4131591 ,
        403.42879349, 1096.63315843])

In [44]:
np.exp ([ 0,1,2,3,4,5])

#e^0 , e^1, e^2, e^3, e^4, e^5

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

##### Flatten

The tool flatten creates a copy of the input array flattened to one dimension.

In [5]:
import numpy

my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print (my_array.flatten())


[1 2 3 4 5 6]


#### intersect1d and delete

https://docs.scipy.org/doc/numpy/reference/generated/numpy.intersect1d.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.delete.html

In [9]:
import numpy as np
x = np.array([1,2,3,4,5,0]).reshape(3,2)
y = np.array([5,6,0,7,8,9]).reshape(2,3)
xy_com , x_ind ,y_ind = np.intersect1d(x,y,return_indices= True)
print (x,y , sep="\n")
print( xy_com, x_ind, y_ind)
print ( np.delete(x,x_ind)  ,np.delete (y , y_ind))

[[1 2]
 [3 4]
 [5 0]]
[[5 6 0]
 [7 8 9]]
[0 5] [5 4] [2 0]
[1 2 3 4] [6 7 8 9]


#### Transpose()

https://stackoverflow.com/questions/5954603/transposing-a-numpy-array

In [1]:
import numpy as np
a = np.array([5,4])[np.newaxis]
print(a)
print(a.T)


[[5 4]]
[[5]
 [4]]
