### Numpy
- Numerical Python
- all Mathematical operations
- Array comes under Numpy

https://numpy.org/

In [1]:
import numpy as np

### Converting List to Array

In [6]:
arr = np.array( [1,2,3,6])
arr

array([1, 2, 3, 6])

#### To check the dimension of an array

In [15]:
arr.ndim

1

#### Number of elements in an array

In [17]:
arr.size  # No. of elements 

7

#### Shape

In [7]:
  arr.shape  # Only count of elements or number of columns/ Rows is alays 1

(4,)

### Converting Tuple to Array

In [48]:
arr = np.array( (1,2,3,6,2,8,9))
print(arr, type (arr) , arr.ndim, arr.size)
arr

[1 2 3 6 2 8 9] <class 'numpy.ndarray'> 1 7


array([1, 2, 3, 6, 2, 8, 9])

#### Mixed Data

Array are sequence of elements of same datatype  i.e they get converted
- int , float --> float
- int , str --> str
- int ,float , str --> str

In [30]:
arr = np.array ( [ 1,4,7, 'f' , 'i '])
print(arr, type (arr))
print ( arr[0], type (arr[0]))
arr

['1' '4' '7' 'f' 'i '] <class 'numpy.ndarray'>
1 <class 'numpy.str_'>


array(['1', '4', '7', 'f', 'i '], dtype='<U11')

In [29]:
arr = np.array ( [ 1,4,5,8.0,4.5])
print(arr, type (arr))
print ( arr[0], type (arr[0]))

[1.  4.  5.  8.  4.5] <class 'numpy.ndarray'>
1.0 <class 'numpy.float64'>


In [32]:
arr = np.array ( [ 1,4,7, 'f' , 'i ', 8.45,4.5])
print(arr, type (arr))
print ( arr[0], type (arr[0]), arr[6], type (arr[6]) )

['1' '4' '7' 'f' 'i ' '8.45' '4.5'] <class 'numpy.ndarray'>
1 <class 'numpy.str_'> 4.5 <class 'numpy.str_'>


#### create an array with specific datatype

In [35]:
data = np.array ( [ 1,3,5,6,8] , dtype = np.float ) # creating float
print(data, type (data[1]) )

[1. 3. 5. 6. 8.] <class 'numpy.float64'>


In [38]:
data = np.array ([ '2', '8' ], dtype = np.int)     # creating int
print(data, type (data[1]) )

[2 8] <class 'numpy.int32'>


In [42]:
data = np.array ([  3.4, 5.6, 6.0, 8.4], dtype = np.int) # converting to int
print(data, type (data[1]) )

[3 5 6 8] <class 'numpy.int32'>


In [52]:
data = np.array ( ['r' , 'ty' ,9, 0 ],dtype = np.str)  #np.str / str  both works. But it is advisable to use np.str
print(data, type (data[1]) )

['r' 'ty' '9' '0'] <class 'numpy.str_'>


#### np.asarray

In [8]:
arr = np.asarray( [ 1,2,3,6,2,8,9 ] )
print(arr, type (arr) , arr.ndim, arr.size,arr.shape)


[1 2 3 6 2 8 9] <class 'numpy.ndarray'> 1 7 (7,)


#### arange()

In [9]:
arr = np.arange ( 1,10,2) 
print(arr , arr.ndim , arr.size, arr.shape , sep ="\t")

[1 3 5 7 9]	1	5	(5,)


In [10]:
arr = np.array ( np.arange ( -10 , -2 ) )
print(arr )
arr = np.arange ( -10 , -2 , 3) 
print(arr , arr.ndim , arr.size, arr.shape , sep ="\t")


[-10  -9  -8  -7  -6  -5  -4  -3]
[-10  -7  -4]	1	3	(3,)


In [71]:
a = range (2,25,2)
arr = np.array(a)
print (arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [3]:
a=np.array(range (2,25,2))
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [4]:
a.shape

(12,)